DMS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from accounts import views

urlpatterns = [
    path("",views.LoginViews.as_view(), name="login"),
    path("admin/", admin.site.urls),
    path("employees/", include("employees.urls")),
    path("user/", include("user.urls")),
    path("dashboard/", include("dashboard.urls")),
    path("dashboard/accounts/", include("accounts.urls")),
    path("farmers/",include("farmers.urls")),
]

dashboard/urls.py
from django.urls import path, include
from . import views


app_name = "dashboard"

urlpatterns = [
    path("", views.dashboardHomeView, name="home"),
    # Employee
    path("employees/active", views.employeeActiveView, name="employees-active"),
    path("employees/inactive", views.employeeInactiveView, name="employees-inactive"),
    path("employees/create", views.employeeCreateView, name="employees-create"),
    path(
        "employees/<int:pk>/update", views.employeeUpdateView, name="employees-update"
    ),
    path(
        "employees/<int:pk>/delete", views.employeeDeleteView, name="employees-delete"
    ),
    # Farmer
    path("farmers/active", views.farmerActiveView, name="farmers-active"),
    path("farmers/inactive", views.farmerInactiveView, name="farmers-inactive"),

    path("farmers/create", views.farmerCreateView, name="farmers-create"),
    path("farmers/<int:pk>/update", views.farmerUpdateView, name="farmers-update"),
    path("farmers/<int:pk>/delete", views.farmerDeleteView, name="farmers-delete"),
    # #FatRate
    # path('fatrates',views.FatRateListView.as_view(), name = 'fatrates-list'),
    # path('fatrates/create',views.fatrateCreateView, name = 'fatrates-create'),
    # path('fatrates/<int:pk>/update',views.fatrateUpdateView, name = 'fatrates-update'),
    # path('fatrates/<int:pk>/delete',views.fatrateDeleteView, name='fatrates-delete'),
    # Milk
    path("milk", views.milkListView, name="milk-list"),
    # path('milk/create',views.milkCreateView, name = 'milk-create'),
    path("milk/<int:pk>/update", views.milkUpdateView, name="milk-update"),
    path("milk/<int:pk>/delete", views.milkDeleteView, name="milk-delete"),
    # Commission
    path("commissions/paid", views.commissionPaidListView, name="commissions-paid"),
    path("commissions/unpaid", views.commissionUnpaidListView, name="commissions-unpaid"),
    path("commissions/<int:pk>/paid", views.commissionPaid, name="commissions-paid"),
    # path('commissions/create',views.commissionCreateView, name = 'commissions-create'),
    path("commissions/<int:pk>/update",views.commissionUpdateView,name="commissions-update"),
    path("commissions/<int:pk>/delete",views.commissionDeleteView,name="commissions-delete"),
    # Payments
    path("payments/paid", views.paidListView, name="payments-paid"),
    path("payments/unpaid", views.unpaidListView, name="payments-unpaid"),
    path("payments/create", views.paymentCreateView, name="payments-create"),
    path("payments/<int:pk>/update", views.paymentUpdateView, name="payments-update"),
    path("payments/<int:pk>/delete", views.paymentDeleteView, name="payments-delete"),
    path("payments/<int:pk>/paid", views.paymentPaidKhalti, name="payments-khalti"),

    # path('payments/esewa-request',views.EsewaRequestView.as_view, name="esewa-request"),
    # path("payments/paid", views.pay, name="payments-paid"),

    # Chart
    path("chart/filter-options/", views.get_filter_options, name="chart-filter-options"),
    path("chart/milks/<int:year>/", views.get_milks_chart, name="chart-sales"),

    #payment
    path('api/verify_payment',views.verify_payment,name='verify_payment'),

    #change password
    path("change_password", views.change_password, name="change_password"),

]

dashboard/models.py
from django.db import models
from django.contrib.auth.models import User
from user.models import *

# Create your models here.


class Commission(models.Model):
    commission_amt = models.PositiveIntegerField(null=True)
    commission_pay_date = models.DateField()
    status = models.CharField(max_length=10, choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid')
    admin_id = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="commission", null=True
    )
    emp_id = models.ForeignKey(
        EmployeeProfile,
        on_delete=models.CASCADE,
        related_name="commission",
        blank=True,
        null=True,
    )

    class Meta:
        verbose_name = "Commission"
        verbose_name_plural = "Commissions"
        ordering = ("id",)

    def __str__(self):
        return self.Commission_amt


# class FatRate(models.Model):
#     rate = models.PositiveBigIntegerField()
#     rate_set_date = models.DateField(blank=True, null=True)
#     admin_id =  models.ForeignKey(User, on_delete=models.CASCADE, related_name='fatrate', blank=False)
#     is_published = models.BooleanField(default=False)

#     class Meta:
#         verbose_name = "FatRate"
#         verbose_name_plural = "FatRates"
#         ordering = ('id',)

#     def __int__(self):
#         return self.rate


class Milk(models.Model):
    fat = models.FloatField()
    qty = models.FloatField()
    rate = models.PositiveIntegerField(null=True)
    date = models.DateField(null=True, blank=True)
    emp_id = models.ForeignKey(
        EmployeeProfile, on_delete=models.CASCADE, related_name="milk_emp", blank=True
    )
    # fatrate_id = models.ForeignKey(FatRate, on_delete=models.CASCADE, related_name='milk', blank=True, null=True)
    farmer_id = models.ForeignKey(FarmerProfile,on_delete=models.CASCADE,related_name="milk_farmer",blank=True,null=True)

    class Meta:
        verbose_name = "Milk"
        verbose_name_plural = "Milk"
        ordering = ("id",)

    def __str__(self):
        return self.fat


class Payment(models.Model):
    amt = models.PositiveIntegerField()
    payment_date = models.DateField()
    status = models.CharField(max_length=10, choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid')
    emp_id = models.ForeignKey(
        EmployeeProfile,
        on_delete=models.CASCADE,
        related_name="payment",
        blank=True,
        null=True,
    )
    admin_id = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="payment_admin",
        blank=True,
        null=True
    )
    farmer_id = models.ForeignKey(
        FarmerProfile,
        on_delete=models.CASCADE,
        related_name="payment_farmer",
        blank=True,
        null=True
    )

    class Meta:
        verbose_name = "Payment"
        verbose_name_plural = "Payments"
        ordering = ("id",)

    def __str__(self):
        return self.amt

dashboard/views.py
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy, reverse
from django.contrib.auth import get_user_model
from datetime import date, timedelta
import re, datetime
from django.contrib.auth.decorators import login_required
from django.db.models import F, Sum
from django.views import View
from .forms import *
from .models import *
from user.models import *
import requests
from django.db.models.functions import ExtractYear, ExtractMonth
from utils.charts import months, colorPrimary, get_year_dict
from django.views.decorators.csrf import csrf_exempt
from django.contrib import messages

User = get_user_model()
# request.session['admin_id'] = User.id
# Create your views here.

   
@login_required(login_url="/dashboard/accounts/login")
def dashboardHomeView(request):
    current_time = datetime.datetime.now().time()
    morning_start_time = datetime.time(6,0)
    afternoon_start_time = datetime.time(12,0)
    evening_start_time = datetime.time(18,0)
    print(current_time)
    if morning_start_time <= current_time < afternoon_start_time:
        message = "Good Morning, "
    elif afternoon_start_time <= current_time < evening_start_time:
        message = "Good Afternoon, "
    else:
        message = "Good Evening, "
    # count employee
    employee_count = EmployeeProfile.objects.filter(is_active=True).count()
    #count Farmer
    farmer_count = FarmerProfile.objects.filter(is_active=True).count()
    # calculate the total milk collected today
    total_milk_collected = Milk.objects.filter(date=date.today()).aggregate(
        total_qty=models.Sum("qty"))["total_qty"]
    # calculate the total milk collected today
    total_amount = Payment.objects.filter(payment_date=date.today(),status='unpaid').aggregate(
        total_amt=models.Sum("amt"))["total_amt"]
    
    return render(
        request,
        "dashboard/index.html",
        {
            "employee_count": employee_count,
            "total_milk_collected": total_milk_collected,
            'total_amount': total_amount,
            'farmer_count': farmer_count,
            'message': message
        }
    )


@login_required(login_url="/dashboard/accounts/login")
def employeeActiveView(request):
    employees = EmployeeProfile.objects.filter(is_active=True)
    return render(request, "dashboard/employees/active.html", {"employees": employees})

@login_required(login_url="/dashboard/accounts/login")
def employeeInactiveView(request):
    employees = EmployeeProfile.objects.filter(is_active=False)
    return render(request, "dashboard/employees/inactive.html", {"employees": employees})

@login_required(login_url="/dashboard/accounts/login")
def employeeCreateView(request):
    # request.session['admin_id']=User.id
    n = ""
    if request.method == "POST":
        emp_email = request.POST.get("emp_email")
        emp_pwd = request.POST.get("emp_pwd")
        emp_name = request.POST.get("emp_name")
        emp_contact = request.POST.get("emp_contact")
        reg_date = request.POST.get("reg_date")

        errors = {}
        # perform Validation
        email_pattern = r"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$"
        if not emp_email:
            errors["emp_email"] = "email field is requied."
        elif not re.match(email_pattern, emp_email):
            errors["emp_email"] = "email is not valid."
        elif EmployeeProfile.objects.filter(emp_email=emp_email).exists():
            errors["emp_email"] = "email is already taken."

        password_pattern = r"^(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}$"
        if not emp_pwd:
            errors["emp_pwd"] = "password field is required."
        elif not re.match(password_pattern, emp_pwd):
            errors[
                "emp_pwd"
            ] = "Invalid password format. It must contain at least 8 characters, including at least one lowercase letter, one uppercase letter, and one digit."

        name_pattern = r"^[A-Za-z\s]+$"
        if not emp_name:
            errors["emp_name"] = "name field is required."
        elif not re.match(name_pattern, emp_name):
            errors["emp_name"] = "Invalid name"
        elif EmployeeProfile.objects.filter(emp_name=emp_name).exists() or User.objects.filter(username = emp_name):
            errors["emp_name"] = "name is already taken."

        contact_pattern = r"^98\d{8}$"
        if not emp_contact:
            errors["emp_contact"] = "contact field is required."
        elif not re.match(contact_pattern, emp_contact):
            errors[
                "emp_contact"
            ] = 'Invalid contact number format. It must start with "98" and have a length of 10 digits.'


        # reg_date_pattern = r'^\d{4}-\d{2}-\d{2}$'
        if not reg_date:
            errors["reg_date"] = "date filed is required."
        else:
            try:
                r_date = date.fromisoformat(reg_date)
                if r_date > date.today():
                    errors["reg_date"] = "Selected date cannot be in future."
            except ValueError:
                errors["reg_date"] = "Invalid date format."

        if errors:
            return render(
                request,
                "dashboard/employees/form.html",
                {
                    "errors": errors,
                    "emp_email": emp_email,
                    "emp_name": emp_name,
                    "emp_pwd": emp_pwd,
                    "emp_name": emp_name,
                    "emp_contact": emp_contact,
                    "reg_date": reg_date,
                },
            )

        else:
            employee = Employee.objects.create_user(
                username=emp_name, email=emp_email, password=emp_pwd
            )

            emp_profile = EmployeeProfile(
                user=employee,
                emp_email=emp_email,
                emp_pwd=emp_pwd,
                emp_name=emp_name,
                emp_contact=emp_contact,
                reg_date=reg_date,
                admin_id=User.objects.get(id=request.session.get("admin_id")),
                salary='15000'
            )
            EmployeeProfile.salary = 15000
            emp_profile.save()
        return redirect(reverse_lazy("dashboard:employees-active"))
    else:
        return render(
            request,
            "dashboard/employees/form.html",
            {
                "admins": User.objects.all(),
            },
        )


@login_required(login_url="/dashboard/accounts/login")
def employeeUpdateView(request, pk):
    employee = get_object_or_404(EmployeeProfile, pk=pk)
    user = employee.user
    admins = User.objects.filter(is_active=True, role= 'ADMIN')
    if request.method == "POST":
        emp_email = request.POST.get("emp_email")
        emp_pwd = request.POST.get("emp_pwd")
        emp_name = request.POST.get("emp_name")
        emp_contact = request.POST.get("emp_contact")
        reg_date = request.POST.get("reg_date")
        # admin_id = User.objects.get(pk=request.POST["admin_id"])
        #validation 
        employee.emp_email= emp_email
        employee.emp_pwd = emp_pwd
        employee.emp_name = emp_name
        employee.emp_contact = emp_contact
        employee.reg_date = reg_date
        employee.save()
        # errors = {}
        # # perform Validation
        # email_pattern = r"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$"
        # if not emp_email:
        #     errors["emp_email"] = "email field is requied."
        # elif not re.match(email_pattern, emp_email):
        #     errors["emp_email"] = "email is not valid."
       

        # password_pattern = r"^(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}$"
        # if not emp_pwd:
        #     errors["emp_pwd"] = "password field is required."
        # elif not re.match(password_pattern, emp_pwd):
        #     errors[
        #         "emp_pwd"
        #     ] = "Invalid password format. It must contain at least 8 characters, including at least one lowercase letter, one uppercase letter, and one digit."

        # name_pattern = r"^[A-Za-z\s]+$"
        # if not emp_name:
        #     errors["emp_name"] = "name field is required."
        # elif not re.match(name_pattern, emp_name):
        #     errors["emp_name"] = "Invalid name"

        # contact_pattern = r"^98\d{8}$"
        # if not emp_contact:
        #     errors["emp_contact"] = "contact field is required."
        # elif not re.match(contact_pattern, emp_contact):
        #     errors[
        #         "emp_contact"
        #     ] = 'Invalid contact number format. It must start with "98" and have a length of 10 digits.'


        # # reg_date_pattern = r'^\d{4}-\d{2}-\d{2}$'
        # if not reg_date:
        #     errors["reg_date"] = "date filed is required."
        # else:
        #     try:
        #         r_date = date.fromisoformat(reg_date)
        #         if r_date > date.today():
        #             errors["reg_date"] = "Selected date cannot be in future."
        #     except ValueError:
        #         errors["reg_date"] = "Invalid date format."
        
        # if errors:
        #     return render(
        #         request,
        #         "dashboard/employees/update_Form.html",
        #         {
        #             "errors": errors,
        #             "emp_email": emp_email,
        #             "emp_name": emp_name,
        #             "emp_pwd": emp_pwd,
        #             "emp_name": emp_name,
        #             "emp_contact": emp_contact,
        #             "reg_date": reg_date,
        #         },
        #     )
        
        # else:
        #     # Update the EmployeeProfile
        #     employee.emp_email = emp_email
        #     employee.emp_pwd = emp_pwd
        #     employee.emp_name = emp_name
        #     employee.emp_contact = emp_contact
        #     # employee.admin_id = admin_id

dashboard/templates/dashboard/base.html
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
  <meta name="generator" content="Hugo 0.108.0">
  <title>Phaijoo Milk Dairy</title>

  <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/dashboard/">
  <link href="/static/dashboard/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
  <link href="/static/dashboard/css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="/static/dashboard/css/dashboard.css" rel="stylesheet">
  
  <!-- khalti static files -->
  <script src="https://khalti.s3.ap-south-1.amazonaws.com/KPG/dist/2020.12.17.0.0.0/khalti-checkout.iffe.js"></script>
  <style>
    .nav-item.dropdown:hover .dropdown-menu {
      display: block;
    }
    .message {
      font-size: 18px;
      font-weight: bold;
      color: #343a40;
      display: flex;
      align-items: center;
    }
    
    .message-text {
      margin-right: 5px;
    }
    
    .username {
      color: #007bff;
    }
    #milkChart {
      max-width: 600px;
      margin: 0 auto;
    }
  </style>
</head>

<body>

  <header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
    <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3 fs-6" href="#">Phaijoo Milk Dairy</a>
    <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse"
      data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbar-nav">
      <div class="nav-item text-nowrap">
        <div class="dropdown-divider"></div>
        <a class="nav-link px-3" href="#" data-toggle="modal" data-target="#logoutModal">
          <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
          Sign out</a>
      </div>
    </div>
  </header>

  <div id="page-top">
    <div class="row">
      <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
        <div class="position-sticky pt-3 sidebar-sticky">
          <ul class="nav flex-column">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'dashboard:home' %}">
                <span data-feather="home" class="align-text-bottom"></span>
                Dashboard
              </a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="commissionDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <span data-feather="layers" class="align-text-bottom"></span>
                Employee
              </a>
              <ul class="dropdown-menu" aria-labelledby="commissionDropdown">
                <li><a class="dropdown-item" href="{% url 'dashboard:employees-active' %}">Active</a></li>
                <li><a class="dropdown-item" href="{% url 'dashboard:employees-inactive' %}">Inactive</a></li>
              </ul>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="commissionDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <span data-feather="layers" class="align-text-bottom"></span>
                Farmer
              </a>
              <ul class="dropdown-menu" aria-labelledby="commissionDropdown">
                <li><a class="dropdown-item" href="{% url 'dashboard:farmers-active' %}">Active</a></li>
                <li><a class="dropdown-item" href="{% url 'dashboard:farmers-inactive' %}">Inactive</a></li>
              </ul>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'dashboard:milk-list' %}">
                <span data-feather="bar-chart-2" class="align-text-bottom"></span>
                Milk
              </a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="commissionDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <span data-feather="layers" class="align-text-bottom"></span>
                Commission
              </a>
              <ul class="dropdown-menu" aria-labelledby="commissionDropdown">
                <li><a class="dropdown-item" href="{% url 'dashboard:commissions-paid' %}">Paid</a></li>
                <li><a class="dropdown-item" href="{% url 'dashboard:commissions-unpaid' %}">Unpaid</a></li>
              </ul>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="paymentDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <span data-feather="layers" class="align-text-bottom"></span>
                Payment
              </a>
              <ul class="dropdown-menu" aria-labelledby="paymentDropdown">
                <li><a class="dropdown-item" href="{% url 'dashboard:payments-paid' %}">Paid</a></li>
                <li><a class="dropdown-item" href="{% url 'dashboard:payments-unpaid' %}">Unpaid</a></li>
              </ul>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'dashboard:change_password' %}">
                <span data-feather="bar-chart-2" class="align-text-bottom"></span>
                Change Password
              </a>
            </li>          
          </ul>


        </div>
      </nav>

      <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
        {% block main %}

        {% endblock main %}

    </div>
    </main>


   <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
      aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
            <button class="close" type="button" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">×</span>
            </button>
          </div>
          <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
          <div class="modal-footer">
            <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
            <a class="btn btn-primary" href="/dashboard/accounts/logout">Logout</a>
          </div>
        </div>
      </div>
    </div>


    <script src="/static/dashboard/js/dashboard.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js"
      integrity="sha384-uO3SXW5IuS1ZpFPKugNNWqTZRRglnUJK6UAZ/gxOX80nxEkN9NcGZTftn6RzhGWE"
      crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js"
      integrity="sha384-zNy6FEbO50N+Cg5wap8IKA4M/ZnLJgzc6w2NqACZaK0u0FXfOWRRJOnQtpZun8ha"
      crossorigin="anonymous"></script>


    <!-- Bootstrap core JavaScript-->
    <script src="/static/dashboard/vendor/jquery/jquery.min.js"></script>
    <script src="/static/dashboard/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="/static/dashboard/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="/static/dashboard/js/sb-admin-2.min.js"></script>

    <!-- Page level plugins -->
    <script src="/static/dashboard/vendor/datatables/jquery.dataTables.min.js"></script>
    <script src="/static/dashboard/vendor/datatables/dataTables.bootstrap4.min.js"></script>

    <!-- Page level custom scripts -->
    <script src="/static/dashboard/js/demo/datatables-demo.js"></script>

    <!-- //delete link script with modal popup -->

    <script>
      $('body').on('click', '.delete-link', function (e) {
        if (!confirm("are you sure You want to delete? "))
          e.preventDefault();
      });
      $('body').on('click', '.pay-link', function (e) {
        if (!confirm("are you sure You want to pay? "))
          e.preventDefault();
      });
    </script>
  </div>
  {% block script %}


    {% endblock script %}
  
</body>

</html>

dashboard/templates/dashboard/change_password.html
{% extends 'dashboard/base.html' %}

{% block main %}
<form class="container mt-3" method="POST" name="change_password" onsubmit="return checkPassword()">
    {% csrf_token %}
    <div class="row mt-4">
        <div class="form-group col-md-6">
            <label><i style="font-weight: bold;">Username</i></label>
            <input type="text" class="form-control mt-2" name="username" value="{{request.user}}" readonly>
        </div>
        <div class="form-group col-md-6">
            <label><i style="font-weight: bold;">Current Password</i></label>
            <input type="password" class="form-control mt-2" name="current_password" placeholder="Current Password" value="{{ current_password }}">
        </div>
    </div>

    <div class="row mt-4">
        <div class="form-group col-md-12">
            <label><i style="font-weight: bold;">New Password</i></label>
            <input type="password" class="form-control mt-2" name="new_password" placeholder="Enter the new password">
            {% if errors.new_password %}
                <p class="error">{{ errors.new_password }}</p>
            {% endif %}
        </div>
    </div>

    <div class="row mt-4">
        <div class="form-group col-md-12">
            <label><i style="font-weight: bold;">Confirm Password</i></label>
            <input type="password" class="form-control mt-2" name="confirm_password" placeholder="Confirm the new password">
            {% if errors.confirm_password %}
                <p class="error">{{ errors.confirm_password }}</p>
            {% endif %}
        </div>
    </div>

    <input type="submit" class="btn btn-outline-primary mt-4" value="Update Password">
</form>

{% if messages %}
    {% for message in messages %}
        <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}
{% endblock %}