DMS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from accounts import views

urlpatterns = [
    path("",views.LoginViews.as_view(), name="login"),
    path("admin/", admin.site.urls),
    path("employees/", include("employees.urls")),
    path("user/", include("user.urls")),
    path("dashboard/", include("dashboard.urls")),
    path("dashboard/accounts/", include("accounts.urls")),
    path("farmers/",include("farmers.urls")),
]

dashboard/urls.py
from django.urls import path, include
from . import views


app_name = "dashboard"

urlpatterns = [
    path("", views.dashboardHomeView, name="home"),
    # Employee
    path("employees/active", views.employeeActiveView, name="employees-active"),
    path("employees/inactive", views.employeeInactiveView, name="employees-inactive"),
    path("employees/create", views.employeeCreateView, name="employees-create"),
    path(
        "employees/<int:pk>/update", views.employeeUpdateView, name="employees-update"
    ),
    path(
        "employees/<int:pk>/delete", views.employeeDeleteView, name="employees-delete"
    ),
    # Farmer
    path("farmers/active", views.farmerActiveView, name="farmers-active"),
    path("farmers/inactive", views.farmerInactiveView, name="farmers-inactive"),

    path("farmers/create", views.farmerCreateView, name="farmers-create"),
    path("farmers/<int:pk>/update", views.farmerUpdateView, name="farmers-update"),
    path("farmers/<int:pk>/delete", views.farmerDeleteView, name="farmers-delete"),
    # #FatRate
    # path('fatrates',views.FatRateListView.as_view(), name = 'fatrates-list'),
    # path('fatrates/create',views.fatrateCreateView, name = 'fatrates-create'),
    # path('fatrates/<int:pk>/update',views.fatrateUpdateView, name = 'fatrates-update'),
    # path('fatrates/<int:pk>/delete',views.fatrateDeleteView, name='fatrates-delete'),
    # Milk
    path("milk", views.milkListView, name="milk-list"),
    # path('milk/create',views.milkCreateView, name = 'milk-create'),
    path("milk/<int:pk>/update", views.milkUpdateView, name="milk-update"),
    path("milk/<int:pk>/delete", views.milkDeleteView, name="milk-delete"),
    # Commission
    path("commissions/paid", views.commissionPaidListView, name="commissions-paid"),
    path("commissions/unpaid", views.commissionUnpaidListView, name="commissions-unpaid"),
    path("commissions/<int:pk>/paid", views.commissionPaid, name="commissions-paid"),
    # path('commissions/create',views.commissionCreateView, name = 'commissions-create'),
    path("commissions/<int:pk>/update",views.commissionUpdateView,name="commissions-update"),
    path("commissions/<int:pk>/delete",views.commissionDeleteView,name="commissions-delete"),
    # Payments
    path("payments/paid", views.paidListView, name="payments-paid"),
    path("payments/unpaid", views.unpaidListView, name="payments-unpaid"),
    path("payments/create", views.paymentCreateView, name="payments-create"),
    path("payments/<int:pk>/update", views.paymentUpdateView, name="payments-update"),
    path("payments/<int:pk>/delete", views.paymentDeleteView, name="payments-delete"),
    path("payments/<int:pk>/paid", views.paymentPaidKhalti, name="payments-khalti"),

    # path('payments/esewa-request',views.EsewaRequestView.as_view, name="esewa-request"),
    # path("payments/paid", views.pay, name="payments-paid"),

    # Chart
    path("chart/filter-options/", views.get_filter_options, name="chart-filter-options"),
    path("chart/milks/<int:year>/", views.get_milks_chart, name="chart-sales"),

    #payment
    path('api/verify_payment',views.verify_payment,name='verify_payment'),

    #change password
    path("change_password", views.change_password, name="change_password"),

]

farmers/urls.py
from django.urls import path

from . import views


app_name = "farmers"

urlpatterns = [
    path("", views.farmerHomeView, name="home"),
    # # payment
    path("payment/due", views.paymentDue, name = "payment-due"),
    path("payment/paid", views.paymentPaid, name = "payment-paid"),
    path("milk/report",views.milkReport, name= "milk-report"),

    #change password
    path("change_password", views.change_password, name="change_password"),
]

dashboard/models.py
from django.db import models
from django.contrib.auth.models import User
from user.models import *

# Create your models here.


class Commission(models.Model):
    commission_amt = models.PositiveIntegerField(null=True)
    commission_pay_date = models.DateField()
    status = models.CharField(max_length=10, choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid')
    admin_id = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="commission", null=True
    )
    emp_id = models.ForeignKey(
        EmployeeProfile,
        on_delete=models.CASCADE,
        related_name="commission",
        blank=True,
        null=True,
    )

    class Meta:
        verbose_name = "Commission"
        verbose_name_plural = "Commissions"
        ordering = ("id",)

    def __str__(self):
        return self.Commission_amt


# class FatRate(models.Model):
#     rate = models.PositiveBigIntegerField()
#     rate_set_date = models.DateField(blank=True, null=True)
#     admin_id =  models.ForeignKey(User, on_delete=models.CASCADE, related_name='fatrate', blank=False)
#     is_published = models.BooleanField(default=False)

#     class Meta:
#         verbose_name = "FatRate"
#         verbose_name_plural = "FatRates"
#         ordering = ('id',)

#     def __int__(self):
#         return self.rate


class Milk(models.Model):
    fat = models.FloatField()
    qty = models.FloatField()
    rate = models.PositiveIntegerField(null=True)
    date = models.DateField(null=True, blank=True)
    emp_id = models.ForeignKey(
        EmployeeProfile, on_delete=models.CASCADE, related_name="milk_emp", blank=True
    )
    # fatrate_id = models.ForeignKey(FatRate, on_delete=models.CASCADE, related_name='milk', blank=True, null=True)
    farmer_id = models.ForeignKey(FarmerProfile,on_delete=models.CASCADE,related_name="milk_farmer",blank=True,null=True)

    class Meta:
        verbose_name = "Milk"
        verbose_name_plural = "Milk"
        ordering = ("id",)

    def __str__(self):
        return self.fat


class Payment(models.Model):
    amt = models.PositiveIntegerField()
    payment_date = models.DateField()
    status = models.CharField(max_length=10, choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid')
    emp_id = models.ForeignKey(
        EmployeeProfile,
        on_delete=models.CASCADE,
        related_name="payment",
        blank=True,
        null=True,
    )
    admin_id = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="payment_admin",
        blank=True,
        null=True
    )
    farmer_id = models.ForeignKey(
        FarmerProfile,
        on_delete=models.CASCADE,
        related_name="payment_farmer",
        blank=True,
        null=True
    )

    class Meta:
        verbose_name = "Payment"
        verbose_name_plural = "Payments"
        ordering = ("id",)

    def __str__(self):
        return self.amt

farmers/models.py
from django.db import models

# Create your models here.

dashboard/views.py
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy, reverse
from django.contrib.auth import get_user_model
from datetime import date, timedelta
import re, datetime
from django.contrib.auth.decorators import login_required
from django.db.models import F, Sum
from django.views import View
from .forms import *
from .models import *
from user.models import *
import requests
from django.db.models.functions import ExtractYear, ExtractMonth
from utils.charts import months, colorPrimary, get_year_dict
from django.views.decorators.csrf import csrf_exempt
from django.contrib import messages

User = get_user_model()
# request.session['admin_id'] = User.id
# Create your views here.

   
@login_required(login_url="/dashboard/accounts/login")
def dashboardHomeView(request):
    current_time = datetime.datetime.now().time()
    morning_start_time = datetime.time(6,0)
    afternoon_start_time = datetime.time(12,0)
    evening_start_time = datetime.time(18,0)
    print(current_time)
    if morning_start_time <= current_time < afternoon_start_time:
        message = "Good Morning, "
    elif afternoon_start_time <= current_time < evening_start_time:
        message = "Good Afternoon, "
    else:
        message = "Good Evening, "
    # count employee
    employee_count = EmployeeProfile.objects.filter(is_active=True).count()
    #count Farmer
    farmer_count = FarmerProfile.objects.filter(is_active=True).count()
    # calculate the total milk collected today
    total_milk_collected = Milk.objects.filter(date=date.today()).aggregate(
        total_qty=models.Sum("qty"))["total_qty"]
    # calculate the total milk collected today
    total_amount = Payment.objects.filter(payment_date=date.today(),status='unpaid').aggregate(
        total_amt=models.Sum("amt"))["total_amt"]
    
    return render(
        request,
        "dashboard/index.html",
        {
            "employee_count": employee_count,
            "total_milk_collected": total_milk_collected,
            'total_amount': total_amount,
            'farmer_count': farmer_count,
            'message': message
        }
    )


@login_required(login_url="/dashboard/accounts/login")
def employeeActiveView(request):
    employees = EmployeeProfile.objects.filter(is_active=True)
    return render(request, "dashboard/employees/active.html", {"employees": employees})

@login_required(login_url="/dashboard/accounts/login")
def employeeInactiveView(request):
    employees = EmployeeProfile.objects.filter(is_active=False)
    return render(request, "dashboard/employees/inactive.html", {"employees": employees})

@login_required(login_url="/dashboard/accounts/login")
def employeeCreateView(request):
    # request.session['admin_id']=User.id
    n = ""
    if request.method == "POST":
        emp_email = request.POST.get("emp_email")
        emp_pwd = request.POST.get("emp_pwd")
        emp_name = request.POST.get("emp_name")
        emp_contact = request.POST.get("emp_contact")
        reg_date = request.POST.get("reg_date")

        errors = {}
        # perform Validation
        email_pattern = r"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$"
        if not emp_email:
            errors["emp_email"] = "email field is requied."
        elif not re.match(email_pattern, emp_email):
            errors["emp_email"] = "email is not valid."
        elif EmployeeProfile.objects.filter(emp_email=emp_email).exists():
            errors["emp_email"] = "email is already taken."

        password_pattern = r"^(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}$"
        if not emp_pwd:
            errors["emp_pwd"] = "password field is required."
        elif not re.match(password_pattern, emp_pwd):
            errors[
                "emp_pwd"
            ] = "Invalid password format. It must contain at least 8 characters, including at least one lowercase letter, one uppercase letter, and one digit."

        name_pattern = r"^[A-Za-z\s]+$"
        if not emp_name:
            errors["emp_name"] = "name field is required."
        elif not re.match(name_pattern, emp_name):
            errors["emp_name"] = "Invalid name"
        elif EmployeeProfile.objects.filter(emp_name=emp_name).exists() or User.objects.filter(username = emp_name):
            errors["emp_name"] = "name is already taken."

        contact_pattern = r"^98\d{8}$"
        if not emp_contact:
            errors["emp_contact"] = "contact field is required."
        elif not re.match(contact_pattern, emp_contact):
            errors[
                "emp_contact"
            ] = 'Invalid contact number format. It must start with "98" and have a length of 10 digits.'


        # reg_date_pattern = r'^\d{4}-\d{2}-\d{2}$'
        if not reg_date:
            errors["reg_date"] = "date filed is required."
        else:
            try:
                r_date = date.fromisoformat(reg_date)
                if r_date > date.today():
                    errors["reg_date"] = "Selected date cannot be in future."
            except ValueError:
                errors["reg_date"] = "Invalid date format."

        if errors:
            return render(
                request,
                "dashboard/employees/form.html",
                {
                    "errors": errors,
                    "emp_email": emp_email,
                    "emp_name": emp_name,
                    "emp_pwd": emp_pwd,
                    "emp_name": emp_name,
                    "emp_contact": emp_contact,
                    "reg_date": reg_date,
                },
            )

        else:
            employee = Employee.objects.create_user(
                username=emp_name, email=emp_email, password=emp_pwd
            )

            emp_profile = EmployeeProfile(
                user=employee,
                emp_email=emp_email,
                emp_pwd=emp_pwd,
                emp_name=emp_name,
                emp_contact=emp_contact,
                reg_date=reg_date,
                admin_id=User.objects.get(id=request.session.get("admin_id")),
                salary='15000'
            )
            EmployeeProfile.salary = 15000
            emp_profile.save()
        return redirect(reverse_lazy("dashboard:employees-active"))
    else:
        return render(
            request,
            "dashboard/employees/form.html",
            {
                "admins": User.objects.all(),
            },
        )


@login_required(login_url="/dashboard/accounts/login")
def employeeUpdateView(request, pk):
    employee = get_object_or_404(EmployeeProfile, pk=pk)
    user = employee.user
    admins = User.objects.filter(is_active=True, role= 'ADMIN')
    if request.method == "POST":
        emp_email = request.POST.get("emp_email")
        emp_pwd = request.POST.get("emp_pwd")
        emp_name = request.POST.get("emp_name")
        emp_contact = request.POST.get("emp_contact")
        reg_date = request.POST.get("reg_date")
        # admin_id = User.objects.get(pk=request.POST["admin_id"])
        #validation 
        employee.emp_email= emp_email
        employee.emp_pwd = emp_pwd
        employee.emp_name = emp_name
        employee.emp_contact = emp_contact
        employee.reg_date = reg_date
        employee.save()
        # errors = {}
        # # perform Validation
        # email_pattern = r"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$"
        # if not emp_email:
        #     errors["emp_email"] = "email field is requied."
        # elif not re.match(email_pattern, emp_email):
        #     errors["emp_email"] = "email is not valid."
       

        # password_pattern = r"^(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}$"
        # if not emp_pwd:
        #     errors["emp_pwd"] = "password field is required."
        # elif not re.match(password_pattern, emp_pwd):
        #     errors[
        #         "emp_pwd"
        #     ] = "Invalid password format. It must contain at least 8 characters, including at least one lowercase letter, one uppercase letter, and one digit."

        # name_pattern = r"^[A-Za-z\s]+$"
        # if not emp_name:
        #     errors["emp_name"] = "name field is required."
        # elif not re.match(name_pattern, emp_name):
        #     errors["emp_name"] = "Invalid name"

        # contact_pattern = r"^98\d{8}$"
        # if not emp_contact:
        #     errors["emp_contact"] = "contact field is required."
        # elif not re.match(contact_pattern, emp_contact):
        #     errors[
        #         "emp_contact"
        #     ] = 'Invalid contact number format. It must start with "98" and have a length of 10 digits.'


        # # reg_date_pattern = r'^\d{4}-\d{2}-\d{2}$'
        # if not reg_date:
        #     errors["reg_date"] = "date filed is required."
        # else:
        #     try:
        #         r_date = date.fromisoformat(reg_date)
        #         if r_date > date.today():
        #             errors["reg_date"] = "Selected date cannot be in future."
        #     except ValueError:
        #         errors["reg_date"] = "Invalid date format."
        
        # if errors:
        #     return render(
        #         request,
        #         "dashboard/employees/update_Form.html",
        #         {
        #             "errors": errors,
        #             "emp_email": emp_email,
        #             "emp_name": emp_name,
        #             "emp_pwd": emp_pwd,
        #             "emp_name": emp_name,
        #             "emp_contact": emp_contact,
        #             "reg_date": reg_date,
        #         },
        #     )
        
        # else:
        #     # Update the EmployeeProfile
        #     employee.emp_email = emp_email
        #     employee.emp_pwd = emp_pwd
        #     employee.emp_name = emp_name
        #     employee.emp_contact = emp_contact
        #     # employee.admin_id = admin_id

dashboard/templates/dashboard/farmers/active.html
{% extends 'dashboard/base.html' %}

{% block main %}
                <!-- Page Heading -->
                <h1 class="h3 mb-2 text-gray-800">Farmer</h1>
                <!-- DataTales Example -->
                <div class="card shadow mb-4">
                    <div class="card-header py-3">
                        <div class="float-right">
                            <a href="{% url 'dashboard:farmers-create' %}" class = "btn btn-primary">
                                <i class="fa fa-plus"></i>&nbsp; Add Farmer
                            </a>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                <thead>
                                    <tr>
                                        <th>SN</th>
                                        <th>Email</th>
                                        <th>Password</th>
                                        <th>Name</th>
                                        <th>Address</th>
                                        <th>Contact</th>
                                        <th>Admin</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                
                                <tbody>
                                    {% for farmer in farmers %}
                                    <tr>
                                        <td>{{ forloop.counter }}</td>
                                        <td>{{ farmer.farmer_email }}</td>
                                        <td>{{ farmer.farmer_pwd }}</td>
                                        <td>{{ farmer.farmer_name }}</td>
                                        <td>{{ farmer.farmer_address }}</td>
                                        <td>{{ farmer.farmer_contact }}</td>
                                        <td>{{ farmer.admin_id }}</td>
                                        <td>
                                            <div class="btn-group" role="group">
                                                <a href="{% url 'dashboard:farmers-update' farmer.pk %}" class="btn btn-info btn-sm ">
                                                    <i class="fas fa-pen"></i>
                                                </a>
                                                {% if not farmer.non_deletetable %}
                                                <form action="{% url 'dashboard:farmers-delete' farmer.pk %}"  method="post">
                                                {% csrf_token %}
                                                    <button class="btn btn-danger btn-sm delete-link ml-2" data-tooltip="tooltip" title="Delete">
                                                        <i class="far fa-trash-alt"></i>
                                                    </button>
                                                </form>
                                                {% endif %}
                                            </div>
                                        </td>
                                    </tr>
                                    {% endfor %}
                                    
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
{% endblock main %}

dashboard/templates/dashboard/farmers/form.html
{% extends 'dashboard/base.html' %}

{% block main %}

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Farmer</h6>
    </div>
    <div class="card-body">
        <form method="post" action="{% url 'dashboard:farmers-create' %}" enctype="multipart/form-data">
            {% csrf_token %}

            <div class="form-group mt-3 ">
                <input type="email" class="form-control" value="{{ farmer_email }}" name="farmer_email" placeholder="Email">
                {% if errors.farmer_email %}
                <p class="error">{{ errors.farmer_email }}</p>
                {% endif %}
            </div>
            <div class="form-group  mt-3">
                <input type="text" class="form-control" value="{{ farmer_pwd }}" name="farmer_pwd" placeholder="Password">
                {% if errors.farmer_pwd %}
                <p class="error">{{ errors.farmer_pwd }}</p>
                {% endif %}
            </div>

            <div class="form-group mt-3">
                <input type="text" class="form-control" value="{{ farmer_name }}" name="farmer_name" placeholder="Farmer Name">
                {% if errors.farmer_name %}
                <p class="error">{{ errors.farmer_name }}</p>
                {% endif %}
            </div>
            <div class="form-group mt-3">
                <input type="text" class="form-control" value="{{ farmer_contact }}" name="farmer_contact" placeholder="Contact">
                {% if errors.farmer_contact %}
                <p class="error">{{ errors.farmer_contact }}</p>
                {% endif %}
            </div>
            <div class="form-group mt-3">
                <input type="text" class="form-control" value="{{ farmer_address }}" name="farmer_address" placeholder="Farmer Address">
                {% if errors.farmer_address %}
                <p class="error">{{ errors.farmer_address }}</p>
                {% endif %}
            </div>
            <!-- <div class="form-group mt-3">
                <select class="form-control" id="inputAddress2" name="admin_id" placeholder="Admin Id">
                    <option value="">Select Admin ID</option>
                    {% for admin in admins %}
                    <option value="{{ admin.id }}">{{ admin.username }}</option>
                    {% endfor %}
                </select>
                {% if errors.admin_id %}
                <p class="error">{{ errors.admin_id }}</p>
                {% endif %}

            </div> -->

    </div>
    <button type="submit" class="btn btn-primary">Save</button>
    </form>
    {% if msg %}
    <h1>{{msg}}</h1>
    {% endif %}
</div>
</div>

{% endblock main %}

dashboard/templates/dashboard/farmers/inactive.html
{% extends 'dashboard/base.html' %}

{% block main %}
                <!-- Page Heading -->
                <h1 class="h3 mb-2 text-gray-800">Farmer</h1>
                <!-- DataTales Example -->
                <div class="card shadow mb-4">
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                <thead>
                                    <tr>
                                        <th>SN</th>
                                        <th>Email</th>
                                        <th>Password</th>
                                        <th>Name</th>
                                        <th>Address</th>
                                        <th>Contact</th>
                                        <th>Admin</th>
                                      
                                    </tr>
                                </thead>
                                
                                <tbody>
                                    {% for farmer in farmers %}
                                    <tr>
                                        <td>{{ forloop.counter }}</td>
                                        <td>{{ farmer.farmer_email }}</td>
                                        <td>{{ farmer.farmer_pwd }}</td>
                                        <td>{{ farmer.farmer_name }}</td>
                                        <td>{{ farmer.farmer_address }}</td>
                                        <td>{{ farmer.farmer_contact }}</td>
                                        <td>{{ farmer.admin_id }}</td>
                                      
                                    </tr>
                                    {% endfor %}
                                    
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
{% endblock main %}

dashboard/templates/dashboard/farmers/list.html
{% extends 'dashboard/base.html' %}

{% block main %}
                <!-- Page Heading -->
                <h1 class="h3 mb-2 text-gray-800">Farmer</h1>
                <!-- DataTales Example -->
                <div class="card shadow mb-4">
                    <div class="card-header py-3">
                        <div class="float-right">
                            <a href="{% url 'dashboard:farmers-create' %}" class = "btn btn-primary">
                                <i class="fa fa-plus"></i>&nbsp; Add Farmer
                            </a>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                <thead>
                                    <tr>
                                        <th>SN</th>
                                        <th>Email</th>
                                        <th>Password</th>
                                        <th>Name</th>
                                        <th>Address</th>
                                        <th>Contact</th>
                                        <th>Admin</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                
                                <tbody>
                                    {% for farmer in farmers %}
                                    <tr>
                                        <td>{{ forloop.counter }}</td>
                                        <td>{{ farmer.farmer_email }}</td>
                                        <td>{{ farmer.farmer_pwd }}</td>
                                        <td>{{ farmer.farmer_name }}</td>
                                        <td>{{ farmer.farmer_address }}</td>
                                        <td>{{ farmer.farmer_contact }}</td>
                                        <td>{{ farmer.admin_id }}</td>
                                        <td>
                                            <div class="btn-group" role="group">
                                                <a href="{% url 'dashboard:farmers-update' farmer.pk %}" class="btn btn-info btn-sm ">
                                                    <i class="fas fa-pen"></i>
                                                </a>
                                                {% if not farmer.non_deletetable %}
                                                <form action="{% url 'dashboard:farmers-delete' farmer.pk %}"  method="post">
                                                {% csrf_token %}
                                                    <button class="btn btn-danger btn-sm delete-link ml-2" data-tooltip="tooltip" title="Delete">
                                                        <i class="far fa-trash-alt"></i>
                                                    </button>
                                                </form>
                                                {% endif %}
                                            </div>
                                        </td>
                                    </tr>
                                    {% endfor %}
                                    
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
{% endblock main %}

dashboard/templates/dashboard/farmers/update_Form.html
{% extends 'dashboard/base.html' %}

{% block main %}

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Farmer</h6>
    </div>
    <div class="card-body">
        <form method="post" action="" enctype="multipart/form-data">
            {% csrf_token %}

            <div class="form-group mt-3 ">
                <input type="email" class="form-control" id="inputEmail4" name="farmer_email" placeholder="Email"
                    value="{{ farmer.farmer_email }}">
            </div>
            <div class="form-group  mt-3">
                <input type="text" class="form-control" id="inputPassword4" name="farmer_pwd" placeholder="Password"
                    value="{{ farmer.farmer_pwd }}">
            </div>

            <div class="form-group mt-3">
                <input type="text" class="form-control" id="inputAddress" name="farmer_name" placeholder="Full Name"
                    value="{{ farmer.farmer_name }}">
            </div>
            <div class="form-group mt-3">
                <input type="text" class="form-control" id="inputAddress2" name="farmer_contact" placeholder="Contact"
                    value="{{ farmer.farmer_contact }}">
            </div>
            <div class="form-group mt-3">
                <input type="text" class="form-control" id="inputAddress2" name="farmer_address" placeholder="Address"
                    value="{{ farmer.farmer_address }}">
            </div>
            <div class="form-group mt-3">
                <select class="form-control" id="inputAddress2" name="admin_id" placeholder="Admin Id">
                    {% for admin in admins %}
                    {% if admin.id == farmer.admin_id_id %}
                    <option value="{{ admin.id }}" selected>{{ admin.username }}</option>
                    {% else %}
                    <option value="{{ admin.id }}">{{ admin.username }}</option>
                    {% endif %}
                    {% endfor %}
                </select>

            </div>

    </div>
    <button type="submit" class="btn btn-primary">update</button>
    </form>
    {% if msg %}
    <h1>{{msg}}</h1>
    {% endif %}
</div>
</div>

{% endblock main %}