DMS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from accounts import views

urlpatterns = [
    path("",views.LoginViews.as_view(), name="login"),
    path("admin/", admin.site.urls),
    path("employees/", include("employees.urls")),
    path("user/", include("user.urls")),
    path("dashboard/", include("dashboard.urls")),
    path("dashboard/accounts/", include("accounts.urls")),
    path("farmers/",include("farmers.urls")),
]

farmers/urls.py
from django.urls import path

from . import views


app_name = "farmers"

urlpatterns = [
    path("", views.farmerHomeView, name="home"),
    # # payment
    path("payment/due", views.paymentDue, name = "payment-due"),
    path("payment/paid", views.paymentPaid, name = "payment-paid"),
    path("milk/report",views.milkReport, name= "milk-report"),

    #change password
    path("change_password", views.change_password, name="change_password"),
]

farmers/models.py
from django.db import models

# Create your models here.

farmers/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
import datetime
from user.models import *
from dashboard.models import Payment,Milk
from django.contrib import messages


# Create your views here.
@login_required(login_url="/dashboard/accounts/farmerlogin")
def farmerHomeView(request):
    current_time = datetime.datetime.now().time()
    morning_start_time = datetime.time(6,0)
    afternoon_start_time = datetime.time(12,0)
    evening_start_time = datetime.time(18,0)
    
    if morning_start_time <= current_time < afternoon_start_time:
        message = "Good Morning, "
    elif afternoon_start_time <= current_time < evening_start_time:
        message = "Good Afternoon, "
    else:
        message = "Good Evening, "

    return render(request, "farmers/index.html",{'message':message})


@login_required(login_url="/dashboard/accounts/farmerlogin")
def paymentDue(request):
    payments =  Payment.objects.filter(farmer_id=request.session.get("farmer_id"),status='unpaid').order_by('-payment_date')
    return render( request, "farmers/payment/due.html",{"payments": payments})

@login_required(login_url="/dashboard/accounts/farmerlogin")
def paymentPaid(request):
    payments =  Payment.objects.filter(farmer_id=request.session.get("farmer_id"),status='paid').order_by('-payment_date')
    return render( request, "farmers/payment/paid.html",{"payments": payments})

@login_required(login_url="/dashboard/accounts/farmerlogin")
def milkReport(request):
    if request.method=="POST":
        start_date = request.POST.get('start_date')
        end_date = request.POST.get('end_date')
        farmer_id = request.session.get("farmer_id")
        milk_datas = Milk.objects.filter(farmer_id=farmer_id, date__range=[start_date, end_date]).order_by('-date')
        print(start_date)
        return render(request, "farmers/milk/report.html",{'datas':milk_datas})
    else:
        display_datas= Milk.objects.filter(farmer_id=request.session.get("farmer_id")).order_by('-date')
        return render(request, "farmers/milk/report.html",{'datas':display_datas})

@login_required(login_url="/dashboard/accounts/farmerlogin")
def change_password(request):
    if request.method == "POST":
        current_password = request.POST['current_password']
        new_password = request.POST['new_password']
        confirm_password = request.POST['confirm_password']
        print(request.session.get("farmer_id"))
        try:
            errors = {}
            password_pattern = r"^(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}$"
            if not new_password:
                errors["new_password"] = "password field is required."
            elif not re.match(password_pattern, new_password):
                errors[
                    "new_password"
                ] = "Invalid password format. It must contain at least 8 characters, including at least one lowercase letter, one uppercase letter, and one digit."

            if not confirm_password:
                errors["confirm_password"] = "password field is required."
            elif not re.match(password_pattern, confirm_password):
                errors[
                    "confirm_password"
                ] = "Invalid password format. It must contain at least 8 characters, including at least one lowercase letter, one uppercase letter, and one digit."

            if errors:
                return render(
                    request,"farmers/change_password.html",
                    {
                        "errors": errors,
                        "current_password":current_password,
                        "new_password":new_password,
                        "confirm_password":confirm_password
                    }
                )

            else:
                u = User.objects.get(id=request.session.get("farmer_id")) 
                
                if u.check_password(current_password) and confirm_password == new_password:
                    u.set_password(new_password)
                    u.save()
                    messages.success(request, 'Password changed successfully!')
                    return render(request, "farmers/change_password.html")
                elif confirm_password!= new_password:
                    messages.error(request, 'confirm password and new password is not same')
                    return render(request, "farmers/change_password.html")
                else:
                    messages.error(request, 'Incorrect current password!')
                    return render(request, "farmers/change_password.html")
                
        except:
            pass
    return render(request, "farmers/change_password.html")
 

farmers/templates/farmers/base.html
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
  <meta name="generator" content="Hugo 0.108.0">
  <title>Phaijoo Milk Dairy</title>
  <script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>
  <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/dashboard/">
  <link href="/static/farmers/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
  <link href="/static/farmers/css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="/static/farmers/css/dashboard.css" rel="stylesheet">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <script src="https://cdn.jsdelivr.net/npm/apexcharts@3.28.3"></script>
  <style>
    .nav-item.dropdown:hover .dropdown-menu {
      display: block;
    }
    .container {
      margin-top: 50px;
    }

    .card-header {
      background-color: #f8f9fa;
      font-weight: bold;
    }

    h2 {
      margin-top: 0;
    }

    .circle-value {
      display: flex;
      justify-content: center;
      align-items: center;
      width: 150px;
      height: 150px;
      border-radius: 50%;
      font-size: 24px;
      font-weight: bold;
      color: #fff;
    }

    .circle-value.payments {
      background-color: #28a745;
    }

    .circle-value.milk {
      background-color: #007bff;

    }

    .circle-value span {
      display: block;
      margin-top: 10px;
    }

    #chart {
      margin-top: 20px;
    }

    .chart-labels {
      display: flex;
      justify-content: space-around;
      margin-top: 20px;
      font-weight: bold;
    }

    .chart-labels .label {
      display: flex;
      align-items: center;
    }

    .chart-labels .label .color-box {
      width: 20px;
      height: 20px;
      margin-right: 10px;
    }
    
      .card {
        background-color: #f8f9fa;
        border-left: 5px solid #007bff;
        padding: 10px;
        border-radius: 5px;
        margin-bottom: 10px;
      }
      
      .message {
        font-size: 18px;
        font-weight: bold;
        color: #343a40;
        display: flex;
        align-items: center;
      }
      
      .message-text {
        margin-right: 5px;
      }
      
      .username {
        color: #007bff;
      }

      
  </style>
</head>

<body>

  <header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
    <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3 fs-6" href="#">Phaijoo Milk Dairy</a>
    <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse"
      data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="dropdown no-arrow " >
      <a class=" btn-lg " href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown"
        aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-ellipsis-v fa-sm fa-fw text-info"></i>
      </a>
      <div class="dropdown-menu  dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
        <a class="dropdown-item nav-link px-3" href="#" data-toggle="modal" data-target="#logoutModal">
          <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-primary"></i>
          Sign out</a>
        <a class="dropdown-item" href="{%url 'farmers:change_password'%}">Change Password</a>
        <!-- <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="#">Something else here</a> -->
      </div>
    </div>
    <!-- <div class="navbar-nav">
      <div class="nav-item text-nowrap">
        <div class="dropdown-divider"></div>
        <a class="nav-link px-3" href="#" data-toggle="modal" data-target="#logoutModal">
          <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
          Sign out</a>
      </div>
      
    </div> -->
  </header>

  <div id="page-top">
    <div class="row">
      <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
        <div class="position-sticky pt-3 sidebar-sticky">
          <ul class="nav flex-column">
            <li class="nav-item">
              <a class="nav-link" aria-current="page" href="{% url 'farmers:home' %}">
                <span data-feather="home" class="align-text-bottom"></span>
                Dashboard
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link " aria-current="page" href="{% url 'farmers:milk-report' %}">
                <span data-feather="book" class="align-text-bottom"></span>
                Milk Report
              </a>
            </li>
            <li class=" dropdown">
              <a class="nav-link dropdown-toggle"  href="#" id="dropdownMenuLink" role="button" data-toggle="dropdown" aria-expanded="false" aria-haspopup="true" >
                <span data-feather="dollar-sign" class="align-text-bottom"></span>
                Payment
              </a>
              <div class="dropdown-menu   shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                <a class="dropdown-item" href="{% url 'farmers:payment-paid' %}">Paid</a>
                <a class="dropdown-item" href="{% url 'farmers:payment-due' %}">Due</a>
               
              </div>
              
            </li>
          </ul>


        </div>
      </nav>

      <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
        {% block main %}

        {% endblock main %}

    </div>
    </main>


    <!-- Logout Modal -->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
      aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
            <button class="close" type="button" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">×</span>
            </button>
          </div>
          <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
          <div class="modal-footer">
            <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
            <a class="btn btn-primary" href="/dashboard/accounts/farmerlogout">Logout</a>
          </div>
        </div>
      </div>
    </div>

    
</body>

</html>

<script src="/static/farmers/js/dashboard.js"></script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js"
  integrity="sha384-uO3SXW5IuS1ZpFPKugNNWqTZRRglnUJK6UAZ/gxOX80nxEkN9NcGZTftn6RzhGWE" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js"
  integrity="sha384-zNy6FEbO50N+Cg5wap8IKA4M/ZnLJgzc6w2NqACZaK0u0FXfOWRRJOnQtpZun8ha" crossorigin="anonymous"></script>
<script src="/static/farmers/js/dashboard.js"></script>


<!-- Bootstrap core JavaScript-->
<script src="/static/farmers/vendor/jquery/jquery.min.js"></script>
<script src="/static/farmers/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

<!-- Core plugin JavaScript-->
<script src="/static/farmers/vendor/jquery-easing/jquery.easing.min.js"></script>

<!-- Custom scripts for all pages-->
<script src="/static/farmers/js/sb-admin-2.min.js"></script>

<!-- Page level plugins -->
<script src="/static/farmers/vendor/datatables/jquery.dataTables.min.js"></script>
<script src="/static/farmers/vendor/datatables/dataTables.bootstrap4.min.js"></script>

<!-- Page level custom scripts -->
<script src="/static/farmers/js/demo/datatables-demo.js"></script>

<!-- //delete link script with modal popup -->

<script>
  $('body').on('click', '.delete-link', function (e) {
    if (!confirm("are you sure You want to delete? "))
      e.preventDefault();
  });
</script>


</body>

</html>

farmers/templates/farmers/change_password.html
{% extends 'farmers/base.html' %}

{% block main %}
<form class="container mt-3" method="POST" name="change_password" onsubmit="return checkPassword()">
    {% csrf_token %}
    <div class="row mt-4">
        <div class="form-group col-md-6">
            <label><i style="font-weight: bold;">Username</i></label>
            <input type="text" class="form-control mt-2" name="username" value="{{request.user}}" readonly>
        </div>
        <div class="form-group col-md-6">
            <label><i style="font-weight: bold;">Current Password</i></label>
            <input type="password" class="form-control mt-2" name="current_password" placeholder="Current Password" value="{{ current_password }}">
        </div>
    </div>

    <div class="row mt-4">
        <div class="form-group col-md-12">
            <label><i style="font-weight: bold;">New Password</i></label>
            <input type="password" class="form-control mt-2" name="new_password" placeholder="Enter the new password">
            {% if errors.new_password %}
                <p class="error">{{ errors.new_password }}</p>
            {% endif %}
        </div>
    </div>

    <div class="row mt-4">
        <div class="form-group col-md-12">
            <label><i style="font-weight: bold;">Confirm Password</i></label>
            <input type="password" class="form-control mt-2" name="confirm_password" placeholder="Confirm the new password">
            {% if errors.confirm_password %}
                <p class="error">{{ errors.confirm_password }}</p>
            {% endif %}
        </div>
    </div>

    <input type="submit" class="btn btn-outline-primary mt-4" value="Update Password">
</form>

{% if messages %}
    {% for message in messages %}
        <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}
{% endblock %}

farmers/templates/farmers/index.html
{% extends 'farmers/base.html' %}

{% block main %}


<div class="card border-left-primary align-items-center">
  <p class="message">
    <span class="message-text">{{ message }}</span>
    <span class="username">{{ request.session.farmer_name }}</span>
  </p>
</div>
<hr>

{% endblock main %}